### ISSUE TITLE
Add a `MetaKernel` class

### ISSUE THREAD

**Issue by dstansby** [dstansby/astrospice#13]
This is a subset of https://github.com/dstansby/astrospice/issues/9. Methods/properties that I think we should implement on the new class:

- `.kernels`, to return a list of the kernel filenames specified in the metakernel
- `.load_kernels()`, to load all of the kernels specified in the metakernel

other ideas welcome!

cc @rlaker

**Comment by rlaker** [comment]
Tried to implement in #14
