### ISSUE TITLE
TypeError: unexpected keyword argument

### ISSUE THREAD

**Issue by MohamedNedal** [dstansby/astrospice#20]
Hello, I got the following error: 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-538a92195058> in <module>
----> 1 kernels = astrospice.registry.get_kernels('psp', 'predict')
      2 psp_kernel = kernels[0]
      3 coverage = psp_kernel.coverage('SOLAR PROBE PLUS')

/opt/anaconda3/lib/python3.7/site-packages/astrospice/net/reg.py in get_kernels(self, body, type, version)
    115             raise ValueError(f'{type} is not one of the known kernel types '
    116                              f'for {body}: {types}')
--> 117         return self._kernels[body][type].get_kernels(version=version)
    118 
    119 

/opt/anaconda3/lib/python3.7/site-packages/astrospice/net/reg.py in get_kernels(self, version)
    214         dl = parfive.Downloader()
    215         for k in kernels:
--> 216             dl.enqueue_file(k.url, get_cache_dir(), k.fname)
    217 
    218         result = dl.download()

/opt/anaconda3/lib/python3.7/site-packages/astrospice/config.py in get_cache_dir()
     15         The absolute path to the cache directory.
     16     """
---> 17     return Path(astropy.config.paths.get_cache_dir(rootname='astrospice'))

TypeError: get_cache_dir() got an unexpected keyword argument 'rootname'

What could be the reason?

**Comment by MohamedNedal** [comment]
Here's another error: 

start_obstime = Time('2019-04-01T00:00:00.000')
end_obstime = Time('2019-04-01T23:51:51.000')

```
dt = TimeDelta(1 * u.day)
times = Time(np.arange(start_obstime, end_obstime, dt))
coords = astrospice.generate_coords('SOLAR PROBE PLUS', times) 
```

---------------------------------------------------------------------------
SpiceSPKINSUFFDATA                        Traceback (most recent call last)
<ipython-input-7-51cb75d8e94b> in <module>
      4 dt = TimeDelta(1 * u.day)
      5 times = Time(np.arange(start_obstime, end_obstime, dt))
----> 6 coords = astrospice.generate_coords('SOLAR PROBE PLUS', times)

/opt/anaconda3/lib/python3.7/site-packages/astrospice/coords.py in generate_coords(body, times)
     29     pos_vel, lightTimes = spiceypy.spkezr(
     30         body.name, times_et, frame, abcorr,
---> 31         'SOLAR SYSTEM BARYCENTER')
     32 
     33     positions = np.array(pos_vel)[:, :3] * u.km

/opt/anaconda3/lib/python3.7/site-packages/spiceypy/spiceypy.py in with_errcheck(*args, **kwargs)
    121     def with_errcheck(*args, **kwargs):
    122         try:
--> 123             res = f(*args, **kwargs)
    124             check_for_spice_error(f)
    125             return res

/opt/anaconda3/lib/python3.7/site-packages/spiceypy/spiceypy.py in spkezr(targ, et, ref, abcorr, obs)
  12002                 targ, ctypes.c_double(t), ref, abcorr, obs, starg, ctypes.byref(lt)
  12003             )
> 12004             check_for_spice_error(None)
  12005             states.append(stypes.c_vector_to_python(starg))
  12006             times.append(lt.value)

/opt/anaconda3/lib/python3.7/site-packages/spiceypy/spiceypy.py in check_for_spice_error(f)
    106         reset()
    107         raise stypes.dynamically_instantiate_spiceyerror(
--> 108             short=short, explain=explain, long=long, traceback=traceback
    109         )
    110 

SpiceSPKINSUFFDATA: 
================================================================================

Toolkit version: CSPICE66

SPICE(SPKINSUFFDATA) --

Insufficient ephemeris data has been loaded to compute the state of -96 (SOLAR PROBE PLUS) relative to 0 (SOLAR SYSTEM BARYCENTER) at the ephemeris epoch 2019 APR 01 00:01:09.185.

spkezr_c --> SPKEZR --> SPKEZ --> SPKGEO

================================================================================

**Comment by rlaker** [comment]
For the second error (SpiceSPKINSUFFDATA), this happens when you have not "furnished" the right spice kernels for that spacecraft.

Make sure you have furnished the kernels with:

`astrospice.registry.get_kernels('psp', 'flown')`

before you try and generate the coordinates. See here for the relevant page in the [docs](https://astrospice.readthedocs.io/en/stable/auto_examples/plot_psp_trajectory.html#sphx-glr-auto-examples-plot-psp-trajectory-py).

**Comment by MohamedNedal** [comment]
> 

@rlaker  I tried that but I got the following error: 

`astrospice.registry.get_kernels('psp', 'flown')
`
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-a5145752c37d> in <module>
----> 1 astrospice.registry.get_kernels('psp', 'flown')

/opt/anaconda3/lib/python3.7/site-packages/astrospice/net/reg.py in get_kernels(self, body, type, version)
    113         types = list(self._kernels[body].keys())
    114         if type not in types:
--> 115             raise ValueError(f'{type} is not one of the known kernel types '
    116                              f'for {body}: {types}')
    117         return self._kernels[body][type].get_kernels(version=version)

ValueError: flown is not one of the known kernel types for psp: ['predict', 'recon'] 
```

When I tried the kernel type 'predict' instead of 'flown', I got this error: 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-8f2c43b09231> in <module>
----> 1 kernels = astrospice.registry.get_kernels('psp', 'predict')

/opt/anaconda3/lib/python3.7/site-packages/astrospice/net/reg.py in get_kernels(self, body, type, version)
    115             raise ValueError(f'{type} is not one of the known kernel types '
    116                              f'for {body}: {types}')
--> 117         return self._kernels[body][type].get_kernels(version=version)
    118 
    119 

/opt/anaconda3/lib/python3.7/site-packages/astrospice/net/reg.py in get_kernels(self, version)
    214         dl = parfive.Downloader()
    215         for k in kernels:
--> 216             dl.enqueue_file(k.url, get_cache_dir(), k.fname)
    217 
    218         result = dl.download()

/opt/anaconda3/lib/python3.7/site-packages/astrospice/config.py in get_cache_dir()
     15         The absolute path to the cache directory.
     16     """
---> 17     return Path(astropy.config.paths.get_cache_dir(rootname='astrospice'))

TypeError: get_cache_dir() got an unexpected keyword argument 'rootname'
```

This is not mentioned on the docs page.

**Comment by rlaker** [comment]
Ok sorry, use either 'pred' or 'recon'.

I don't know what is causing the second error.

**Comment by MohamedNedal** [comment]
> 'pred' or 'recon'

@rlaker  I tried both 'pred' and 'recon' and they produce the second error.

**Comment by dstansby** [comment]
For the second issue, could you open a new issue? That way it's easier to track both issues.

For the first one, it lookslike the error is coming from astropy. What version of `astropy` do you have installed?

**Comment by MohamedNedal** [comment]
@dstansby Done, I opened a new issue for the second problem. I have: 
```
astropy.__version__ = 3.1.2 
astrospice.__version__ = 0.1.0 
```

**Comment by dstansby** [comment]
I think this is because you're using an old version of astropy; astrospice only supports astropy versions >= 4.2. Can you upgrade and try again?

**Comment by MohamedNedal** [comment]
@dstansby  That's correct, I've upgraded astropy and now the error is gone! 
Thank you very much!
